title: Your awesome title
email: narek [dot] asadorian [at] gmail [dot] com
description: >-
  exceptionally mediocre functional programmer
baseurl: ""
url: "https://nasadorian.github.io"
twitter_username: portal_narlish
github_username:  nasadorian

# Build settings
theme: no-style-please
plugins:
  - jekyll-feed

# Github API
github: [metadata]

# Theme
theme_config:
  appearance: "dark"
